apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: YOUR_AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/meeting-backend:latest
        ports:
        - containerPort: 8221
        env:
          - name: DB_HOST
            value: "<DB_HOST_PLACEHOLDER>"
          - name: DB_NAME
            value: "meetingdb"
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: password
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - port: 8221
    targetPort: 8221
