pipeline {
    agent any

    environment {
        AWS_REGION = "us-east-1"
        AWS_ACCOUNT_ID = "379322108224"
        ECR_REPO = "my-frontend-repo"
        IMAGE_TAG = "latest"
        REPOSITORY_URI = "379322108224.dkr.ecr.us-east-1.amazonaws.com/my-frontend-repo"
    }

    stages {
        stage('code checkout') {
            steps {
                echo "Cloning Repository..."
                git branch: 'main', url: 'https://github.com/anumularoots-svg/pro.git'
            }
        }

        stage('AWS Login to ECR') {
            steps {
                script {
                    sh """
                    aws ecr get-login-password --region ${AWS_REGION} | \
                    docker login --username AWS --password-stdin ${REPOSITORY_URI}
                    """
                }
            }
        }

        stage('docker build') {
            steps {
                sh "docker build -t ${ECR_REPO}:${IMAGE_TAG} -f frontend/Dockerfile ."
            }
        }

        stage('docker tag') {
            steps {
                sh "docker tag ${ECR_REPO}:${IMAGE_TAG} ${REPOSITORY_URI}:${IMAGE_TAG}"
            }
        }

        stage('docker push') {
            steps {
                sh "docker push ${REPOSITORY_URI}:${IMAGE_TAG}"
            }
        }
    }
}
