pipeline {
    agent any

    environment {
        AWS_REGION = "us-east-1"
        AWS_ACCOUNT_ID = "379322108224"
        ECR_REPO = "my-frontend-repo"
        IMAGE_TAG = "latest"
        ECR_URL = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
    }

    stages {
        stage('Checkout Code') {
            steps {
                echo "Cloning Repository..."
                git branch: 'main', url: 'https://github.com/anumularoots-svg/pro.git'
            }
        }

        stage('AWS Login to ECR') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'aws-creds', usernameVariable: 'AWS_ACCESS_KEY_ID', passwordVariable: 'AWS_SECRET_ACCESS_KEY')]) {
                    sh '''
                        export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
                        export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY

                        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
                        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
                        aws configure set default.region ${AWS_REGION}

                        aws ecr get-login-password --region ${AWS_REGION} \
                        | docker login --username AWS --password-stdin ${ECR_URL}
                    '''
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                echo "Building Docker Image..."
                sh "docker build -t ${ECR_REPO}:latest ."
            }
        }

        stage('Tag Docker Image') {
            steps {
                echo "Tagging Docker Image..."
                sh "docker tag ${ECR_REPO}:latest ${ECR_URL}/${ECR_REPO}:${IMAGE_TAG}"
            }
        }

        stage('Push to ECR') {
            steps {
                echo "Pushing Docker Image to ECR..."
                sh "docker push ${ECR_URL}/${ECR_REPO}:${IMAGE_TAG}"
            }
        }
    }

    post {
        success {
            echo '✅ Build & Push to ECR Successful'
        }
        failure {
            echo '❌ Build Failed. Check logs.'
        }
    }
}
